INSERT INTO CHAT_FORBIDDEN_WORDS (id, content)
VALUES (1,'Teste');
INSERT INTO CHAT_FORBIDDEN_WORDS (id, content)
VALUES (2,'Teste2');
INSERT INTO CHAT_FORBIDDEN_WORDS (id, content)
VALUES (3,'Teste3');
